class AddMoviesForSummer2016 < ActiveRecord::Migration
  def change
  reversible do |dir|
      dir.up do
        season = Season.where(name:'Summer 2016').first
        
        Movie.create(name:'Captain America: Civil War',
          plot:'Political interference in the Avengers\' activities causes a rift between former allies Captain America and Iron Man.',
          actors:'Robert Downey Jr., Chris Evans, Scarlett Johansson',
          release_date:'2016-5-6',
          director:'Anthony and Joe Russo',
          imdb:'http://www.imdb.com/title/tt3498820',
          rotten_tomatoes_id:'771377017',
          season_id: season.id)
        Movie.create(name:'Kidnap',
          plot:'A mother stops at nothing to recover her kidnapped son.',
          actors:'Halle Berry, Christopher Berry, Dana Gourrier',
          release_date:'2016-5-13',
          director:'Luis Prieto',
          imdb:'http://www.imdb.com/title/tt1458169',
          rotten_tomatoes_id:'771390116',
          season_id: season.id)
        Movie.create(name:'Money Monster',
          plot:'An irate investor takes a bombastic financial TV show host hostage live on the air after losing everything due to his bad advice.',
          actors:'George Clooney, Julia Roberts, Jack O\'Connell',
          release_date:'2016-5-13',
          director:'Jodie Foster',
          imdb:'http://www.imdb.com/title/tt2241351',
          rotten_tomatoes_id:'771423060',
          season_id: season.id)
        Movie.create(name:'The Angry Birds Movie',
          plot:'When an island populated by happy, flightless birds is visited by mysterious green pigs, it\'s up to three unlikely outcasts to figure out what they are up to.',
          actors:'Jason Sudeikis, Josh Gad, Peter Dinklage',
          release_date:'2016-5-20',
          director:'Clay Kaytis, Fergal Reilly',
          imdb:'http://www.imdb.com/title/tt1985949',
          rotten_tomatoes_id:'771356127',
          season_id: season.id)
        Movie.create(name:'Neighbors 2: Sorority Rising',
          plot:'After a sorority moves in next door, which is even more debaucherous than the fraternity before it, Mac and Kelly have to ask for help from their former enemy, Teddy.',
          actors:'Zac Efron, Selena Gomez, Seth Rogen',
          release_date:'2016-5-20',
          director:'Nicholas Stoller',
          imdb:'http://www.imdb.com/title/tt4438848',
          rotten_tomatoes_id:'771413677',
          season_id: season.id)
        Movie.create(name:'The Nice Guys',
          plot:'A private eye investigates the apparent suicide of a fading porn star in 1970s Los Angeles and uncovers a conspiracy.',
          actors:'Ryan Gosling, Kim Basinger, Russell Crowe',
          release_date:'2016-5-20',
          director:'Shane Black',
          imdb:'http://www.imdb.com/title/tt3799694',
          rotten_tomatoes_id:'771384010',
          season_id: season.id)
        Movie.create(name:'Alice Through the Looking Glass',
          plot:'Alice returns to the whimsical world of Wonderland and travels back in time to save the Mad Hatter.',
          actors:'Johnny Depp, Anne Hathaway',
          release_date:'2016-5-27',
          director:'James Bobin',
          imdb:'http://www.imdb.com/title/tt2567026',
          rotten_tomatoes_id:'771370508',
          season_id: season.id)
        Movie.create(name:'X-Men: Apocalpyse',
          plot:'With the emergence of the world\'s first mutant, Apocalypse, the X-Men must unite to defeat his extinction level plan.',
          actors:'Jennifer Lawrence, Michael Fassbender, Olivia Munn',
          release_date:'2016-5-27',
          director:'Bryan Singer',
          imdb:'http://www.imdb.com/title/tt3385516',
          rotten_tomatoes_id:'771371217',
          season_id: season.id)
        Movie.create(name:'Popstar: Never Stop Never Stopping',
          plot:'When his new album fails to sell records, pop/rap superstar conner4real is forced to reunite with his old group.',
          actors:'Andy Samberg, Imogen Poots, Sarah Silverman',
          release_date:'2016-6-3',
          director:'Akiva Schaffer, Jorma Taccone',
          imdb:'http://www.imdb.com/title/tt3960412',
          rotten_tomatoes_id:'771420457',
          season_id: season.id)
        Movie.create(name:'Teenage Mutant Ninja Turtles: Out of the Shadows',
          plot:'The Turtles return to save the city from a dangerous threat.',
          actors:'Alan Ritchson, Megan Fox',
          release_date:'2016-6-3',
          director:'Dave Green',
          imdb:'http://www.imdb.com/title/tt3949660',
          rotten_tomatoes_id:'771386622',
          season_id: season.id)
        Movie.create(name:'The Conjuring 2',
          plot:'Lorraine and Ed Warren travel to north London to help a single mother raising four children alone in a house plagued by malicious spirits.',
          actors:'Vera Farmiga, Patrick Wilson',
          release_date:'2016-6-10',
          director:'James Wan',
          imdb:'http://www.imdb.com/title/tt3065204',
          rotten_tomatoes_id:'771375842',
          season_id: season.id)
        Movie.create(name:'Now You See Me 2',
          plot:'The Four Horsemen resurface for a comeback performance in hopes of exposing the unethical practices of a tech magnate.',
          actors:'Mark Ruffalo, Daniel Radcliffe, Jesse Eisenberg',
          release_date:'2016-6-10',
          director:'John M. Chu',
          imdb:'http://www.imdb.com/title/tt3110958',
          rotten_tomatoes_id:'771362372',
          season_id: season.id)
        Movie.create(name:'Warcraft',
          plot:'An epic fantasy adventure based on the popular video game series.',
          actors:'Travis Fimmel, Ben Foster, Paula Patton',
          release_date:'2016-6-10',
          director:'Duncan Jones',
          imdb:'http://www.imdb.com/title/tt0803096',
          rotten_tomatoes_id:'771021948',
          season_id: season.id)
        Movie.create(name:'Central Intelligence',
          plot:'After he reunites with an old pal through Facebook, a mild-mannered accountant is lured into the world of international espionage.',
          actors:'Dwayne Johnson, Aaron Paul, Kevin Hart',
          release_date:'2016-6-17',
          director:'Rawson Marshall Thurber',
          imdb:'http://www.imdb.com/title/tt1489889',
          rotten_tomatoes_id:'771403192',
          season_id: season.id)
        Movie.create(name:'Finding Dory',
          plot:'The friendly-but-forgetful blue tang fish reunites with her loved ones.',
          actors:'Ellen DeGeneres, Idris Elba, Michael Sheen',
          release_date:'2016-6-17',
          director:'Andrew Stanton, Angus MacLane',
          imdb:'http://www.imdb.com/title/tt2277860',
          rotten_tomatoes_id:'771353630',
          season_id: season.id)
        Movie.create(name:'Free State of Jones',
          plot:'As civil war divides the nation, a poor farmer from Mississippi leads a group of rebels against the Confederate army.',
          actors:'Matthew McConaughey, Gugu Mbatha-Raw',
          release_date:'2016-6-24',
          director:'Gary Ross',
          imdb:'http://www.imdb.com/title/tt1124037',
          rotten_tomatoes_id:'771414367',
          season_id: season.id)
        Movie.create(name:'Independence Day: Resurgence',
          plot:'Two decades after the first Independence Day invasion, Earth is faced with a new extra-Solar threat.',
          actors:'Jeff Goldblum, Liam Hemsworth, Bill Pullman',
          release_date:'2016-6-24',
          director:'Roland Emmerich',
          imdb:'http://www.imdb.com/title/tt1628841',
          rotten_tomatoes_id:'771359352',
          season_id: season.id)
        Movie.create(name:'The BFG',
          plot:'Sophie meets the Big Friendly Giant, a kindhearted soul who is considered an outcast by the other giants because he refuses to eat boys and girls.',
          actors:'Rebecca Hall, Mark Rylance',
          release_date:'2016-7-1',
          director:'Steven Spielberg',
          imdb:'http://www.imdb.com/title/tt3691740',
          rotten_tomatoes_id:'771382797',
          season_id: season.id)
        Movie.create(name:'The Legend of Tarzan',
          plot:'Tarzan, having acclimated to life in London, is called back to his former home in the jungle to investigate the activities at a mining encampment.',
          actors:'Alexander Skarsgård, Margot Robbie, Samuel L. Jackson',
          release_date:'2016-7-1',
          director:'David Yates',
          imdb:'http://www.imdb.com/title/tt0918940',
          rotten_tomatoes_id:'771374700',
          season_id: season.id)
        Movie.create(name:'The Purge: Election Year',
          plot:'Sgt. Barnes has become head of security for the front runner in the next Presidential election, due to her vow to eliminate the Purge.',
          actors:'Elizabeth Mitchell, Frank Grillo',
          release_date:'2016-7-1',
          director:'James DeMonaco',
          imdb:'http://www.imdb.com/title/tt4094724',
          rotten_tomatoes_id:'771411544',
          season_id: season.id)
        Movie.create(name:'Mike & Dave Need Wedding Dates',
          plot:'Two brothers place an online ad, which goes viral, to find dates for a wedding.',
          actors:'Anna Kendrick, Zac Efron, Aubrey Plaza',
          release_date:'2016-7-8',
          director:'Jake Szymanski',
          imdb:'http://www.imdb.com/title/tt2823054',
          rotten_tomatoes_id:'771410851',
          season_id: season.id)
        Movie.create(name:'The Secret Life of Pets',
          plot:'Max\'s life as a favorite pet is turned upside down, when his owner brings home a sloppy mongrel named Duke.',
          actors:'Kevin Hart, Lake Bell, Louis C.K.',
          release_date:'2016-7-8',
          director:'Chris Renaud, Yarrow Cheney',
          imdb:'http://www.imdb.com/title/tt2709768',
          rotten_tomatoes_id:'771350404',
          season_id: season.id)
        Movie.create(name:'Ghostbusters',
          mapped_name:'Ghostbusters (2016)',
          plot:'30 years after Ghostbusters took the world by storm, the beloved franchise makes its long-awaited return.',
          actors:'Kristen Wiig, Melissa McCarthy, Chris Hemsworth',
          release_date:'2016-7-15',
          director:'Paul Feig',
          imdb:'http://www.imdb.com/title/tt1289401',
          rotten_tomatoes_id:'770808377',
          season_id: season.id)
        Movie.create(name:'Ice Age: Collision Course',
          plot:'Scrat accidentally sets off a series of cosmic events that transform and threaten the planet.',
          actors:'Melissa Rauch, Denis Leary, Jennifer Lopez',
          release_date:'2016-7-22',
          director:'Mike Thurmeier, Galen T. Chu',
          imdb:'http://www.imdb.com/title/tt3416828',
          rotten_tomatoes_id:'771372077',
          season_id: season.id)
        Movie.create(name:'Star Trek Beyond',
          plot:'',
          actors:'Chris Pine, Zoe Saldana, Simon Pegg',
          release_date:'2016-7-22',
          director:'Justin Lin',
          imdb:'http://www.imdb.com/title/tt2660888',
          rotten_tomatoes_id:'771361911',
          season_id: season.id)
        Movie.create(name:'Jason Bourne',
          plot:'',
          actors:'Matt Damon, Julia Stiles, Tommy Lee Jones',
          release_date:'2016-7-29',
          director:'Paul Greengrass',
          imdb:'http://www.imdb.com/title/tt4196776',
          rotten_tomatoes_id:'771398975',
          season_id: season.id)
        Movie.create(name:'The Space Between Us',
          plot:'A young man raised by scientists on Mars returns to Earth to find his father.',
          actors:'Britt Robertson, Gary Oldman, Carla Gugino',
          release_date:'2016-7-29',
          director:'Peter Chelsom',
          imdb:'http://www.imdb.com/title/tt3922818',
          rotten_tomatoes_id:'771434794',
          season_id: season.id)
        Movie.create(name:'The Founder',
          plot:'The story of McDonald\'s founder Ray Kroc.',
          actors:'Michael Keaton, Linda Cardellini, Patrick Wilson',
          release_date:'2016-8-5',
          director:'John Lee Hancock',
          imdb:'http://www.imdb.com/title/tt4276820',
          rotten_tomatoes_id:'771414950',
          season_id: season.id)
        Movie.create(name:'Suicide Squad',
          plot:'A secret government agency recruits imprisoned supervillains to execute dangerous black ops missions in exchange for clemency.',
          actors:'Margot Robbie, Will Smith, Jared Leto',
          release_date:'2016-8-5',
          director:'David Ayer',
          imdb:'http://www.imdb.com/title/tt1386697',
          rotten_tomatoes_id:'771400429',
          season_id: season.id)
        Movie.create(name:'Pete\'s Dragon',
          plot:'A young orphan seeks refuge from his abusive adoptive parents with the help of a pet dragon and a couple who live in a lighthouse.',
          actors:'Bryce Dallas Howard, Robert Redford',
          release_date:'2016-8-12',
          director:'David Lowery',
          imdb:'http://www.imdb.com/title/tt2788732',
          rotten_tomatoes_id:'771411737',
          season_id: season.id)
      end
      
      dir.down do
        season = Season.where(name:'Summer 2016').first
        Movie.where(season_id: season.id).destroy_all
      end
    end
  end
end
